# Generated by Django 5.0.6 on 2024-05-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privilege',
            field=models.CharField(default='User', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
