# Generated by Django 5.0.6 on 2024-05-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_privilege_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('nutritionist_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('license_id', models.CharField(max_length=50)),
                ('schedule_day', models.CharField(max_length=300)),
                ('schedule_time', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Nutritionist',
            },
        ),
    ]
