# Generated by Django 5.0.6 on 2024-05-22 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_nutritionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('nutritionist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='api.nutritionist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='api.user')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
