# Generated by Django 5.0.6 on 2024-05-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shopmealplan_shopmeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmealplan',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
