# Generated by Django 5.0.6 on 2024-05-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_shopmealplan_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopmeal',
            old_name='meal_id',
            new_name='shop_meal_id',
        ),
        migrations.RenameField(
            model_name='shopmealplan',
            old_name='mealplan_id',
            new_name='shop_mealplan_id',
        ),
    ]
