# Generated by Django 5.0.6 on 2024-05-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_meal_id_shopmeal_shop_meal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmeal',
            name='carbs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
