# Generated by Django 5.0.6 on 2024-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_shopmeal_carbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmeal',
            name='day',
            field=models.CharField(default='Sunday', max_length=15),
            preserve_default=False,
        ),
    ]
