# Generated by Django 5.0.6 on 2024-05-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shopmeal_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmealplan',
            name='end_week',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shopmealplan',
            name='start_week',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
