# Generated by Django 5.0.6 on 2024-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_shopmealplan_end_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmealplan',
            name='end_week',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shopmealplan',
            name='start_week',
            field=models.DateField(),
        ),
    ]
