# Generated by Django 5.0.6 on 2024-05-31 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_shopmealplan_end_week_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shopmeal',
            table=None,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('orders', models.JSONField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingss', to='api.user')),
            ],
            options={
                'db_table': 'shop_meal',
            },
        ),
    ]
