# Generated by Django 5.0.6 on 2024-05-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_shopmeal_table_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
