# Generated by Django 5.0.6 on 2024-05-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_cart_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shopmeal',
            table='shop_meal',
        ),
    ]
