# Generated by Django 5.0.6 on 2024-06-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_shopmealplan_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('default', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingsss', to='api.user')),
            ],
        ),
    ]
