# Generated by Django 5.0.6 on 2024-06-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
    ]
