# Generated by Django 5.0.6 on 2024-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postalcode',
            field=models.CharField(default=1234, max_length=15),
            preserve_default=False,
        ),
    ]
