# Generated by Django 5.0.6 on 2024-06-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_address_postalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('orders', models.JSONField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=35)),
                ('payment', models.CharField(max_length=35)),
                ('shipping', models.CharField(max_length=35)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingsss1', to='api.address')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingsss1', to='api.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
