# Generated by Django 5.0.6 on 2024-06-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(default='n/a', max_length=400),
            preserve_default=False,
        ),
    ]
