# Generated by Django 5.0.6 on 2024-06-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
