# Generated by Django 5.0.6 on 2024-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
