# Generated by Django 5.0.6 on 2024-06-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_foodentry_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='journal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listingsss2', to='api.journalentry'),
            preserve_default=False,
        ),
    ]
