# Generated by Django 5.0.6 on 2024-06-08 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_foodentry_journal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='user_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='listingsss4', to='api.user'),
            preserve_default=False,
        ),
    ]
