# Generated by Django 5.0.6 on 2024-06-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_journalentry_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
