# Generated by Django 5.0.6 on 2024-06-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default='http://127.0.0.1:8000/Photos/profile.png', max_length=300),
            preserve_default=False,
        ),
    ]
