# Generated by Django 5.0.6 on 2024-06-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_nutritionist_schedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionist',
            name='schedule_time',
        ),
    ]
