# Generated by Django 5.0.6 on 2024-06-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_nutritionist_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionist',
            name='schedule_time',
            field=models.JSONField(default=['3:00pm-5:00pm, 9:00 am - 11:00am', '5:00 pm-7:00pm']),
            preserve_default=False,
        ),
    ]
