# Generated by Django 5.0.6 on 2024-06-30 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_nutritionist_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledeck',
            name='nutritionist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingsss3', to='api.nutritionist'),
        ),
    ]
