# Generated by Django 5.0.6 on 2024-07-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_verifynutritionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifynutritionist',
            name='email',
            field=models.CharField(default='somethign@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
