# Generated by Django 5.0.6 on 2024-07-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_verifynutritionist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifynutritionist',
            name='phone',
            field=models.CharField(default='012345678901', max_length=15),
            preserve_default=False,
        ),
    ]
