# Generated by Django 5.0.6 on 2024-07-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_verifynutritionist_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
