# Generated by Django 5.0.6 on 2024-07-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifynutritionist',
            name='license_id',
            field=models.CharField(default='123456789', max_length=20),
            preserve_default=False,
        ),
    ]
