# Generated by Django 5.0.6 on 2024-07-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_nutritionist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionist',
            name='license_pic',
            field=models.CharField(default='http://127.0.0.1:8000/Photos/license/GQc7Xw8XAAAHE0F_8QmbYvx.jfif', max_length=200),
            preserve_default=False,
        ),
    ]
