# Generated by Django 5.0.6 on 2024-07-05 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_nutritionist_license_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionist',
            name='user_id',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='listings5', to='api.user'),
            preserve_default=False,
        ),
    ]
