# Generated by Django 5.0.6 on 2024-07-14 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_nutritionist_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedMeal',
            fields=[
                ('generatedMeal_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal', models.JSONField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingsss10', to='api.user')),
            ],
            options={
                'db_table': 'generated_meal',
            },
        ),
    ]
