# Generated by Django 5.0.6 on 2024-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_generatedmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmeal',
            name='name',
            field=models.CharField(default='none', max_length=40),
            preserve_default=False,
        ),
    ]
