# Generated by Django 5.0.6 on 2024-07-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_generatedmeal_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmeal',
            name='cuisine',
            field=models.JSONField(default=['none', 'none']),
            preserve_default=False,
        ),
    ]
