# Generated by Django 5.0.6 on 2024-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_generatedmeal_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lang',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='longi',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
