# Generated by Django 5.0.6 on 2024-07-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_address_lang_address_longi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lang',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='longi',
            field=models.FloatField(),
        ),
    ]
