# Generated by Django 5.0.6 on 2024-08-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_address_lang_alter_address_longi'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.JSONField(default=['random', 'random']),
            preserve_default=False,
        ),
    ]
