# Generated by Django 5.0.6 on 2024-08-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_order_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='schedule_date',
            field=models.JSONField(default=['july 30', 'aug 4']),
            preserve_default=False,
        ),
    ]
