# Generated by Django 5.0.6 on 2024-08-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_order_schedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMeals',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('generatedMeal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingsss100', to='api.generatedmeal')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingsss100', to='api.user')),
            ],
            options={
                'db_table': 'request_meals',
            },
        ),
    ]
