# Generated by Django 5.0.6 on 2024-08-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_requestmeals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('primaryColor', models.CharField(max_length=50)),
                ('secondaryColor', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'theme',
            },
        ),
    ]
