# Generated by Django 5.0.6 on 2024-08-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_requestmeals_status_deployedorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployedorder',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='deployedorder',
            name='user_id',
        ),
    ]
