# Generated by Django 5.0.6 on 2024-08-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_deployedorder_address_deployedorder_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeals',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
