# Generated by Django 5.0.6 on 2024-08-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_requestmeals_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmealplan',
            name='image',
            field=models.CharField(max_length=3000),
        ),
    ]
