# Generated by Django 5.0.6 on 2024-08-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_shopmealplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmeal',
            name='image',
            field=models.CharField(max_length=3000),
        ),
    ]
