# Generated by Django 5.0.6 on 2024-08-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_shopmeal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmeal',
            name='food',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shopmealplan',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
