# Generated by Django 5.0.6 on 2024-08-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_shopmeal_food_alter_shopmealplan_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table=None,
        ),
        migrations.AlterModelTable(
            name='appointment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='journalentry',
            table=None,
        ),
        migrations.AlterModelTable(
            name='meeting',
            table=None,
        ),
        migrations.AlterModelTable(
            name='nutritionist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shopmeal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shopmealplan',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
