# Generated by Django 5.0.6 on 2024-08-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_address_table_alter_appointment_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='Appointment',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='journalentry',
            table='journal_entry',
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='meeting',
        ),
        migrations.AlterModelTable(
            name='nutritionist',
            table='Nutritionist',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='shopmeal',
            table='shop_meal',
        ),
        migrations.AlterModelTable(
            name='shopmealplan',
            table='shop_meal_plan',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
