# Generated by Django 5.0.6 on 2024-08-23 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_appointment_table_alter_nutritionist_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiling',
            fields=[
                ('profiling_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('common_sys', models.IntegerField()),
                ('common_dia', models.IntegerField()),
                ('hypertension', models.BooleanField(default=0)),
                ('dateofBP', models.DateField()),
                ('takingMeds', models.BooleanField(default=0)),
                ('targetCalories', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings67', to='api.user')),
            ],
            options={
                'db_table': 'profiling',
            },
        ),
    ]
