# Generated by Django 5.0.6 on 2024-09-12 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_profiling'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNutritionistAgreement',
            fields=[
                ('agree_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patient_nutritionist_agreement',
            },
        ),
        migrations.AlterField(
            model_name='shopmealplan',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.CreateModel(
            name='PendingAppointment',
            fields=[
                ('pending_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('nutritionist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings8', to='api.nutritionist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings8', to='api.user')),
            ],
            options={
                'db_table': 'pending_appointment',
            },
        ),
    ]
