# Generated by Django 5.0.6 on 2024-09-12 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_patientnutritionistagreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnutritionistagreement',
            name='nutritionist_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='listings15', to='api.nutritionist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientnutritionistagreement',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings15', to='api.user'),
            preserve_default=False,
        ),
    ]
