# Generated by Django 5.0.6 on 2024-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_patientnutritionistagreement_nutritionist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingappointment',
            name='time',
            field=models.TimeField(default='05:30:00.000000'),
            preserve_default=False,
        ),
    ]
