# Generated by Django 5.0.6 on 2024-09-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_pendingappointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendMealPlan',
            fields=[
                ('recommend_mealplan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=3000)),
                ('description', models.CharField(max_length=2000)),
                ('start_week', models.DateField()),
                ('end_week', models.DateField()),
                ('nutritionist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingsss123', to='api.nutritionist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingsss123', to='api.user')),
            ],
            options={
                'db_table': 'recommend_meal_plan',
            },
        ),
        migrations.CreateModel(
            name='RecommendMeal',
            fields=[
                ('recommend_meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('food', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=3000)),
                ('day', models.CharField(max_length=15)),
                ('recommend_mealplan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings56', to='api.recommendmealplan')),
            ],
            options={
                'db_table': 'recommend_meal',
            },
        ),
    ]
