# Generated by Django 5.0.6 on 2024-09-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_appointment_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendmealplan',
            name='end_week',
        ),
        migrations.RemoveField(
            model_name='recommendmealplan',
            name='start_week',
        ),
    ]
