# Generated by Django 5.0.6 on 2024-05-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_videocall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocall',
            name='id',
        ),
        migrations.AddField(
            model_name='videocall',
            name='video_id',
            field=models.AutoField(default='null', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
