# Generated by Django 5.0.6 on 2024-05-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_videocall_id_videocall_video_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='videocall',
            table='VideoCalls',
        ),
    ]
