# Generated by Django 5.0.6 on 2024-05-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_videocall_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
