# Generated by Django 5.0.6 on 2024-05-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_videocall'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'VideoCall',
            },
        ),
    ]
