# Generated by Django 5.0.6 on 2024-05-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_videocall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
