# Generated by Django 5.0.6 on 2024-05-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_videocalls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.DeleteModel(
            name='VideoCalls',
        ),
    ]
