# Generated by Django 5.0.6 on 2024-05-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_videocalls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoCalls',
            new_name='VideoCall',
        ),
        migrations.AlterModelTable(
            name='videocall',
            table='VideoCall',
        ),
    ]
