# Generated by Django 5.0.6 on 2024-05-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_videocalls_videocall_alter_videocall_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
